name: train_val_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip
  - requests
  - scikit-learn=1.7.2
  - pip:
      - mlflow==3.3.2
      - wandb==0.22.0
      - -e ..
