name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - requests
  - scikit-learn=1.7.2
  - pandas=2.3.2
  - pip:
      - mlflow==3.3.2
      - wandb==0.22.0
      - -e ..
