name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.10.6
  - pandas=2.3.2
  - pip
  - scikit-learn=1.7.2
  - pip:
      - mlflow==3.3.2
      - wandb==0.22.0
